### ISSUE TITLE
[init] 개발환경 세팅

### ISSUE THREAD

**Issue by HongJungKim-dev** [dnd-side-project/dnd-5th-8-frontend#1]
## Todo
- [x] node 설치
React native는 javascript기반으로 동작하기 때문에 js 런타임인 node가 필요합니다.
- [x] open jdk 설치
Android 앱을 빌드하기 위하여 설치합니다.
- [x] python 설치
React native 빌드 시스템은 python에 의존하여 설치하여야합니다.
- [x] React Native CLI 설치
- [x] 안드로이드 스튜디오 설치
- [ ] webpack 설정
- [ ] eslint 세팅
- [ ] prittier 세팅 

## 특이사항
설치는 완료했으나 앱 실행에 오류가 발생하여 해결중입니다,

**Comment by HongJungKim-dev** [comment]
expo는 iOS없이 맥만으로 아이폰 테스트가 가능하여 expo로 변경하였습니다.
